name: Example
permissions:
  contents: read
  pull-requests: write

on:
  push:
    branches:
      - main
    paths:
      - 'examples/**'
      - '.github/workflows/example.yml'

  pull_request:
    paths:
      - 'examples/**'
      - '.github/workflows/example.yml'

jobs:
  build:
    name: Check C99 examples
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v6

    - name: Compile example-star.c
      run: |
        gcc -c -Wall -Werror -Iinclude examples/c99/example-star.c

    - name: Compile example-high-z.c
      run: |
        gcc -c -Wall -Werror -Iinclude examples/c99/example-high-z.c

    - name: Compile example-orbital.c
      run: |
        gcc -c -Wall -Werror -Iinclude examples/c99/example-orbital.c

    - name: Compile example-time.c
      run: |
        gcc -c -Wall -Werror -Iinclude examples/c99/example-time.c
        
    - name: Compile example-rise-set.c
      run: |
        gcc -c -Wall -Werror -Iinclude examples/c99/example-rise-set.c

  build-cpp:
    name: Check C++ examples
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v6

    - name: Compile example-star.cpp
      run: |
        g++ -c -Wall -Werror -Iinclude examples/cpp/example-star.cpp

    - name: Compile example-high-z.cpp
      run: |
        g++ -c -Wall -Werror -Iinclude examples/cpp/example-high-z.cpp

    - name: Compile example-time.cpp
      run: |
        g++ -c -Wall -Werror -Iinclude examples/cpp/example-time.cpp

